* <<<CPXXXX>>> PRINCIPLES OF DATA SCIENCE
:properties:
:author: Dr. Y. V. Lokeswai
:date: 02-May-2022
:end:

#+startup: showall


{{{credits}}}
|L|T|P|C|
|3|0|0|3|

** Course Objectives
- To learn fundamentals of Data Science using Python.
- To develop python program for analysis of data using Python libraries.
- To develop python programs for manipulating and visualizing the data.
- To understand probability and Statistics for the data.
- To be familiar with supervised and unsupervised methods in machine learning.


{{{unit}}}
|Unit I|INTRODUCTION TO DATA SCIENCE |9| 
Introduction: Need for data science –- Benefits and uses -– Facets of data–Data science process: Retrieving data –- Cleansing, integrating and transforming data –- Exploratory Data Analysis –- Build the models –- Presenting findings and building applications.

{{{unit}}}
|Unit II|PYTHON LIBRARIES FOR DATA SCIENCE |9| 
NumPy Basics: Arrays and Vectorized Computation -- The NumPy ndarray -- Creating ndarrays -- Data Types for ndarrays -- Arithmetic with NumPy Arrays -- Basic Indexing and Slicing -- Boolean Indexing -- Transposing Arrays and Swapping Axes. Introduction to pandas Data Structures: Series, DataFrame -- Essential Functionality: Dropping Entries -- Indexing, Selection, and Filtering -- Function Application and Mapping- Sorting and Ranking. Summarizing and Computing Descriptive Statistics -- Unique Values, Value Counts, and Membership. Reading and Writing Data in Text Format.

{{{unit}}}
|Unit III|DATA CLEANING, PREPARATION AND VISUALIZATION |9| 
Data Cleaning and Preparation: Handling Missing Data -- Data Transformation: Removing Duplicates, Transforming Data Using a Function or Mapping, Replacing Values, Detecting and Filtering Outliers- String Manipulation: Vectorized String Functions in pandas. Plotting with pandas and matplotlib: Line Plots, Bar Plots, Histograms and Density Plots, Scatter or Point Plots.

{{{unit}}}
|Unit IV|STATISTICAL ANALYSIS |9| 
Introduction –- Data Preparation –- Exploratory Data Analysis: Data summarization –- Data distribution –- Outlier Treatment –- Measuring asymmetry –- Continuous distribution; Estimation: Mean –- Variance –- Sampling –- Covariance –- Correlation, Measuring the Variability in Estimates: Point estimates –- Confidence intervals; Hypothesis Testing: Using confidence intervals –- Using p-values


{{{unit}}}
|Unit V|DATA ANALYSIS |9|
Machine learning –- Modeling Process –- Training model –- Validating model –- Predicting new observations –- Supervised learning algorithms -– Linear Regression -- Unsupervised learning algorithms –- K Means Clustering –- Reinforcement learning.

\hfill *Total: 45*

** Course Outcomes
After the completion of this course, students will be able to
- Demonstrate the need and the fundamental concepts of data science. (K2)
- Develop Python programs to perform analysis on data using Python libraries. (K3)
- Develop Python programs for data preparation and visualizing the data. (K3)
- Interpret the various statistical inferences (K2)
- Develop applications to demonstrate data analysis in practice (K3)

      
** TEXT BOOKS
1. Davy Cielen, Arno D B Meysman, Mohamed Ali, ``Introducing Data Science – Big data,
Machine Learning, and more using Python tools'', Manning Publications Co, 2016.
2. Wes McKinney, ``Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython”,
O’Reilly, 2nd Edition,2018.
3. Laura Igual, Santi Segua, ``Introduction to Data Science – A Python Approach to Concepts,
Techniques and Applications'', Springer Nature, 2017

** REFERENCE BOOKS
1. Jake VanderPlas, ``Python Data Science Handbook: ``Essential Tools for Working with Data'',
O'Reilly Media, 2016.
2. Foster Provost, Tom Fawcett, ``Data Science for Business'', O'Reilly Media, 2013
3. Rachel Schutt, Cathy O'Neil, ``Doing Data Science'', O'Reilly Media, 2016

      
   ** CO PO MAPPING 
#+NAME: co-po-mapping
|                |    |PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | 
|                |    | K3 | K6  |  K6 |  K6 | K6  |     |     |     |     |      |      |     
| CO1            | K2 |  2 |  1  |     |     |     |     |     |     |     |      |      |    
| CO2            | K3 |  3 |  2  |     |     |  2  |     |     |     |     |      |      |  
| CO3            | K3 |  3 |  2  |     |     |  2  |     |     |     |     |      |      |    
| CO4            | K2 |  2 |  1  |     |     |  1  |     |     |     |     |      |      |    
| CO5            | K3 |  3 |  2  |     |     |  2  |     |     |     |     |      |      |   
| Total          |    | 13 |  8  |     |     |  7  |     |     |     |     |      |      |   
| Course Mapping |    |  3 |  2  |     |     |  2  |     |     |     |     |      |      |     


