* <<<CP1211>>> DATA SCIENCE LAB
:properties:
:author: Dr. Y. V. Lokeswari
:date: 02-May-2022
:end:

#+startup: showall
 
{{{credits}}}
|L|T|P|C|
|0|0|3|1.5|

** Course Objectives
- To get familiar with the python programming for data science
- To develop python programs for data preparation and manipulation using NumPy and Pandas.
- To construct python programs for data visualization
- To make use of python packages for statistical analysis
- To get familiar with machine learning algorithms.


** Suggestive Experiments
*** Python
1. Implement basic data types and user defined functions using Python.
i.	Implement basic Python programs for reading input from console.
ii.	Perform Creation, indexing, slicing, concatenation, and repetition operations on Python built-in data types: Strings, List, Tuples, Dictionary, Set
iii.	Apply Python built-in data types: Strings, List, Tuples, Dictionary, Set and their methods to solve any given problem 
iv.	Handle numerical operations using math and random number functions
v.	Create user-defined functions with different types of function arguments.
***Files with Python
2. Develop python programs for packages and working on files.
i.	Create packages and import modules from packages.
ii.	Perform File manipulations- open, close, read, write, append and copy from one file to another.

*** NumPy

3.  Perform basic computations and manipulation on arrays using NumPy package.
i.	Create NumPy arrays from Python Data Structures, Intrinsic NumPy objects and Random Functions.
ii.	Manipulation of NumPy arrays- Indexing, Slicing, Reshaping, Joining and Splitting.
iii.	Computation on NumPy arrays using Universal Functions and Mathematical methods.

4.  Perform manipulations on the CSV files and images using NumPy package.

i.	Import a CSV file and perform various Statistical and Comparison operations on rows/columns.
ii.	Load an image file and do crop and flip operation using NumPy Indexing.

*** Pandas
5. Perform data manipulation on the input CSV file using Pandas Package.
i.	Create Pandas Series and DataFrame from various inputs.
ii.	Import any CSV file to Pandas DataFrame and perform the following:
a)	Visualize the first and last 10 records
b)	Get the shape, index and column details
c)	Select/Delete the records(rows)/columns based on conditions.
d)	Perform ranking and sorting operations.
e)	Do required statistical operations on the given columns.
f)	Find the count and uniqueness of the given categorical values.
g)	Rename single/multiple columns.

*** Visualization

6. Perform data preparation and visualization on the input CSV file using Pandas matplotlib pacakages.

i.	Import any CSV file to Pandas DataFrame and perform the following:
a)	Handle missing data by detecting and dropping/ filling missing values.
b)	Transform data using apply() and map() method.
c)	Detect and filter outliers.
d)	Perform Vectorized String operations on Pandas Series.
e)	Visualize data using Line Plots, Bar Plots, Histograms, Density Plots and Scatter Plots.

*** Statistical Analysis.
7. Perform Exploratory Data Analysis on a CSV file.
Import any CSV file and perform Exploratory Data Analysis: Data summarization,  
8. Compute the following for the given data set using NumPy package. Compute Mean, Variance, Standard Deviation, Sampling, Covariance, Correlation.

*** Machine Learning
9. Download data from UCI Machine Learning Repository and perform the supervised learning algorithm. Implement the Linear Regression for the given application.

10. Download data from UCI Machine Learning Repository and perform the unsupervised learning algorithm. Implement the K Means Clustering algorithm for the given application.



\hfill *Total: 60*

** Course Outcomes
After the completion of this course, students will be able to: 
- Demonstrate the fundamentals in python (K2)
- Analyze the significance of python packages for data creation and manipulation (K4)
- Experiment the methods of data handling and visualization through NumPy, Pandas and MatplotLib modules (K3).
- Construct Python programs for obtaining statistical inference on data. (K3)
- Develop machine learning algorithms for real world application. (K3)


  ** CO PO MAPPING 
#+NAME: co-po-mapping
|                |    |PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | 
|                |    | K3 | K6  |  K6 |  K6 | K6  |     |     |     |     |      |      |     
| CO1            | K2 |  2 |  1  |  1  |     |  1  |     |     |     |     |      |      |    
| CO2            | K4 |  3 |  2  |  2  |     |  2  |     |     |     |     |      |      |  
| CO3            | K3 |  3 |  2  |  2  |     |  2  |     |     |     |     |      |      |  
| CO4            | K3 |  3 |  2  |  2  |     |  2  |     |     |     |     |      |      |  
| CO5            | K3 |  3 |  2  |  2  |     |  2  |     |     |     |     |      |      |  
| Total          |    | 14 |  9  |  9  |     |  9  |     |     |     |     |      |      |   
| Course Mapping |    |  3 |  2  |  2  |     |  2  |     |     |     |     |      |      |
