
:properties:
:author: Suresh J
:date: 04.05.2022										
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE                | L | T | P | C |
|      | WEB APPLICATION DEVELOPMENT | 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand the concepts of web site development
- To learn web application development using Javascript based framework
- To learn web application development using Python based framework


{{{unit}}}
| UNIT I | INTRODUCTION | 5 |
Web Essentials: Web clients, web servers, communication protocol, HTTP request and response message; HTML5: Tables - Lists - Image – Control and semantic elements – CSS3 - Inline, embedded and external style sheets – Rule cascading – Backgrounds – Colors – Text – Transformations – Transitions – Animations.

{{{unit}}}
| UNIT II | CLIENT SIDE PROGRAMMING | 5 |
Introduction to JavaScript – Variables – Data types– Statements – Operators – Functions – Objects – Arrays – Built-in objects – Event handling.

{{{unit}}}
| UNIT III | ANGULARJS | 8 |
Introduction to Angular – Typescript: Built-in types, classes – Components: Decorator, input, output – Built-in Directives: NgIf, NgFor, NgSwitch, NgStyle, NgClass – Forms: Using FormBuilder, Adding Validations  – HTTP API – Routing: Components of Routing, Nested routes – Services: Observables and RxJS. Implementation 

{{{unit}}}
| UNIT IV | NODEJS & EXPRESSJS  | 6 |
Getting Started with NodeJS; Introduction to Express; Saving time with Express: Scaffolding – views and layouts – Static files and views– Dynamic content in views; Request and Response Objects; Templating with Handlebars.

{{{unit}}}
|Unit V|PYTHON BASED FRAMEWORK - DJANGO  |6|
Introduction to Django: Django Template System – Interacting with Database (Models) – Building Simple Django Applications – Message Board App – Blog App;  Form Processing; Configuring Heroku Account – Deploying Projects in Heroku: Newspaper App – Advanced Views and URL Confs.

\hfill *Total: 30*

** Suggested Mini-projects
•	Create a college website using HTML5 and CSS3
•	Develop a MVC based web application for a Super Market Billing System. 
•	Develop online exam web application using AngularJS
•	Develop a web application for personal website using ExpressJS
•	Develop a web application for student information system that allows to perform CRUD operations using ExpressJS and MySQL
•	Develop Library Management System using MVC Django Architecture

\hfill *Total: 15*

** COURSE OUTCOMES
After the completion of this course, students will be able to:
- Build a website using HTML and CSS (K3). 
- Outline client-side programming (K2)
- Develop web application using AngularJS MVW framework (K3). 
- Develop web application using java script-based framework (K3). 
- Examine the web applications build using Python based framework (K4).


** REFERENCES
1. Jeffrey C Jackson, Web Technologies A Computer Science Perspective, Pearson Education, 2011. (Unit I) 
2.	Deitel and Deitel, Nieto, Internet and World Wide Web - How to Program, Prentice Hall, 5th Edition, 2011. (Unit II) 
3.	Nate Murray, Felipe Coury, Ari Lerner, and Carlos , “Ng-book: The Complete Guide to Angular” ,  Fullstack.io, 2020 (Unit III)
4.	Ethan Brown, “Development with Node and Express”, O’Reilly, 1st Edition, 2014 (Unit IV)
5.	Adrian Holovaty, Jacob K Moss, “Django – The definitive Guide to Django”, Apress Publishers, 2008. (Unit V)

