* <<<PE>>> ADVANCED NETWORKS
:properties:
:author: V. S. Felix Enigo
:date: 06 May 2022
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 2 | 0 | 0 | 3 |

** Course Objectives
- To study the network fundamentals.
- To explore various technologies in the wireless domain. 
- To study about Cellular and 4G networks.
- To understand the paradigm of software defined networks.

{{{unit}}}
| Unit I | Network Fundamentals | 9 |
Introduction –- Networking Hardware -– Network Cabling -– Wireless Networking -– IP addressing -– Protocols -– The Internet

{{{unit}}}
| Unit II | Wireless Networks | 9 |
IEEE802.16 and WiMAX -- Security -- Advanced 802.16 functionalities -- Mobile WiMAX:802.16e -- Network infrastructure -- WLAN Configurations -- Management operations -- IEEE 802.11e and WMM – Quality of Service

{{{unit}}}
| Unit III | Cellular Networks | 9 |
GSM Introduction –- Mobility management and call control -– GPRS State model -– Network elements -– Mobility management and session management -- Small Screen Web Browsing over GPRS and EDGE -– MMS over GPRS

{{{unit}}}
| Unit IV | 4G Networks | 9 |
LTE -- Network architecture and interfaces -- Mobility management and power optimization -- LTE security architecture -- Interconnection
with UMTS and GSM -- 4G networks and composite radio environment -- Protocol boosters -- Hybrid 4G wireless networks protocols.

{{{unit}}}
| Unit V | Software Defined Networks | 9 |
Introduction -- Centralized and distributed control and data planes –- OpenFlow -- Wire protocol – Hybrid Approaches – SDN Controllers.  


\hfill *Total: 45*

** References
1. James Bernstein, “Networking made Easy”, 2018. (Unit - I) 
2. Martin Sauter, ``From GSM to LTE, An Introduction to Mobile Networks and Mobile Broadband'', Wiley, 2014. (Unit – II, III, IV)
3. Savo G Glisic, ``Advanced Wireless Networks -- 4G Technologies'',   John Wiley & Sons, 2006. (Unit – IV)
4. Thomas D. Nadeau and Ken Gray, ``SDN -- Software Defined Networks'',    O'Reilly Publishers, 2013. (Unit – V)


** Course Outcomes
After the completion of this course, students will be able to: 
- Explain the fundamentals of networking (K2).
- Develop networks using different wireless network technologies (K3).
- Analyse the working of GSM network (K4)
- Analyse the use of various 4G Networks (K4).
- Demonstrate the working of software defined networks (K2).
