* 
:properties:
:author: J. SURESH
:date: 26 April 2022
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE            | L | T | P | C |
|      | BLOCKCHAIN TECHNOLOGIES | 3 | 0 | 0 | 3 |


** COURSE OBJECTIVES
- To understand blockchain technology and distributed systems
- To learn how decentralization of trust is achieved
- To study the technologies behind cryptocurrencies
- To impart knowledge of distributed ledgers in business
- To acquire knowledge in emerging concepts using blockchain

{{{unit}}}
| UNIT I | INTRODUCTION TO BLOCKCHAIN | 9 |
Defining the Terms - Building blocks of Blockchain frameworks - Where is and where it’s going - Blockchain in Enterprise - Technology Considerations - Identity - Scalability - Security - Consensus - CAP - ACID Property - Benefits and Limitation of Blockchain.

{{{unit}}}
|UNIT II|DECENTRALIZATION|9|
Methods of Decentralization – Routes to Decentralization – Smart Contract – Decentralized Organization – Platforms for Decentralization – Consensus Algorithms.

{{{unit}}}
|UNIT III|CRYTOCURRENCIES|9|
Digital Money - Cryptography; Cryptocurrencies - Bitcoin - Ethereum; Digital Token; Alternative Coins

{{{unit}}}
|UNIT IV|DISTRIBUTED LEDGERS FOR BUSINESS|9|
Ethereum: Introduction – Ethereum Network – Components – Programming Languages; Hyperledger: Introduction – Reference Architecture – Fabric – Sawtooth Lake – Corda.

{{{unit}}}
| UNIT V | BLOCKCHAIN DEVELOPMENT TOOLS AND FRAMEWORKS | 9 |
Compilers: Solidity – Ganache – Metamask – Truffle; Languages: Solidity – Go – Java – NodeJS; Blockchain Use Case: Financials – Insurance - Supply Chain Management – HealthCare – IoT.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to:
- Explain the  importance of distributed ledgers and need of blockchain (K2)
- Describe decentralisation concepts and apply consensus algorithms (K3)
- Explain the basics of cryptography and its applications in cryptocurrencies (K2)
- Apply various distributed ledgers for business (K4)
- Make use of appropriate techniques for designing trust-based business networks (K4)


** REFERENCES
- Nitin Gaur, Luc Desrosiers, Petr Novotny, Venkatraman Ramakrishna, "Hands-on Blockchain with Hyperledger", Packt Publishers, 2018. (Unit I & IV)
- Antony Lewis, "The basics of Bitcoins and Blockchains", Mango Publishing, Coral Gabels (Unit III)
- Imran Bashir, “Mastering Blockchain” Packt 2nd Edition, 2018. (Unit II, IV & V)
- Kevin Solorio, Randall Kanna, David H. Hoover, "Hands-On Smart Contract Development with Solidity and Ethereum: From Fundamentals to Deployment", First Edition, OReilly Publications, 2019.
- Will Button, "Hands-On Blockchain Development in 7 Days: Create a decentralized gaming application using Ethereum Paperback", Packt Publishers, 2019.


** CO TO PO MAPPING
| PO/PSO | 1 | 2 | 3 | 4 |
|--------+---+---+---+---|
| CO1    |   |   |   |   |
| CO2    |   |   |   |   |
| CO3    |   |   |   |   |
| CO4    |   |   |   |   |
| CO5    |   |   |   |   |
|--------+---+---+---+---|
| Course |   |   |   |   |
   
