* <<<CP1322>>> SOFTWARE PROJECT MANAGEMENT
:properties:
:author:  Angel Deborah S
:date: 27 April 2022   
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objective

- Understand the basic concept of project management
- Learn the various costing and life cycle management
- Understand the role played by risk in software project
- Appreciate the use of metrics for software project management
- Know the challenges in people management



{{{unit}}}
|Unit I|Project Management |9|
Software Project Management: Approaches - Project acquisition - Initiation - Planning - Execution - Execution control - Change management - Scheduling - Project closure
{{{unit}}}
|Unit II|Process Models & Lifecycle Management|9|
Introduction to life cycle models - Agile development models - Extreme programming - Scrum; Project planning - Metrics of project size estimation - Project estimation techniques - Empirical estimation techniques - COCOMO  - Halstead - Staffing level; ISO 9000 - SEI CMM -SPICE - PSP

{{{unit}}}
|Unit III|Risk Management|9|
Perspectives of Risk Management - Risk Definition – Risk Categories – Risk Assessment: Approaches, techniques and good practices – Risk Identification / Analysis / Prioritization – Risk Control (Planning / Resolution / Monitoring) – Risk Retention – Risk Transfer - Failure Mode and Effects Analysis (FMEA) – Operational Risks – Supply Chain Risk Management.

{{{unit}}}
|Unit IV|Metrics|9|
Need for Software Metrics: scope, basics, framework for software measurement - Product Metrics: Size Metrics, Complexity Metrics, Halsteads Product Metrics, Quality Metrics- Process metrics: Empirical Models, Statistical Models,Theory based Models,Composite Models, Reliability Models- Measuring Internal and External
Product Attributes.

{{{unit}}}
|Unit V|People Management|9|
Leadership styles – Developing Leadership skills – Leadership assessment – Motivating People – Organizational strategy – Management – Team building – Delegation – Art of Interviewing People - Team Management – Rewarding - Client Relationship Management.

\hfill *Total: 45*

** Course Outcome

- Summarize the various steps involved in software project management(K2)
- Choose an appropriate process model and estimate project cost and effort required(K5)
- Identify existing risk and perform risk assessment (K3)
- Choose appropriate software metric for software project management (K3)
- Outline leadership styles and team building. (K2)




** References
1. Murali Chemuturi, Thomas M. Cagley, ``Mastering Software Project Management: Best Practices, Tools and Techniques'', J. Ross Publishing, 2010.(UNIT I)
2. Rajib Mall, ``Fundamentals of Software Engineering'', 3rd edition, PHI Learning Pvt. Ltd., 2009.(UNIT II)
3. Ravindranath Pandian, ``Applied Software Risk Management A Guide for Software Project Managers'', Auerbach Publication, 2007. (UNIT III)
4. Antonio Borghesi, Barbara Gaudenzi, ``Risk Management: How to Assess, Transfer and Communicate Critical Risks: Perspectives in Business Culture'',Illustrated Edition, Springer, 2012. (UNIT III)
5. Norman Fenton, James Bieman, ``Software Metrics: A Rigorous and Practical Approach'', 3rd edition, CRC Press, 2015.(UNIT IV)
6. Bob Hughes, Mike Cotterell, Rajib Mall, ``Software Project Management'', Sixth  Edition, Tata McGraw Hill, 2018.(UNIT I, V)

